// NBA team arenas (home team ID -> arena info)
export const NBA_ARENAS: Record<number, { arena: string; city: string }> = {
  1: { arena: "State Farm Arena", city: "Atlanta" },
  2: { arena: "TD Garden", city: "Boston" },
  3: { arena: "Barclays Center", city: "Brooklyn" },
  4: { arena: "Spectrum Center", city: "Charlotte" },
  5: { arena: "United Center", city: "Chicago" },
  6: { arena: "Rocket Mortgage FieldHouse", city: "Cleveland" },
  7: { arena: "American Airlines Center", city: "Dallas" },
  8: { arena: "Ball Arena", city: "Denver" },
  9: { arena: "Little Caesars Arena", city: "Detroit" },
  10: { arena: "Chase Center", city: "San Francisco" },
  11: { arena: "Toyota Center", city: "Houston" },
  12: { arena: "Gainbridge Fieldhouse", city: "Indianapolis" },
  13: { arena: "Intuit Dome", city: "Inglewood" },
  14: { arena: "Crypto.com Arena", city: "Los Angeles" },
  15: { arena: "FedExForum", city: "Memphis" },
  16: { arena: "Kaseya Center", city: "Miami" },
  17: { arena: "Fiserv Forum", city: "Milwaukee" },
  18: { arena: "Target Center", city: "Minneapolis" },
  19: { arena: "Smoothie King Center", city: "New Orleans" },
  20: { arena: "Madison Square Garden", city: "New York" },
  21: { arena: "Paycom Center", city: "Oklahoma City" },
  22: { arena: "Kia Center", city: "Orlando" },
  23: { arena: "Wells Fargo Center", city: "Philadelphia" },
  24: { arena: "Footprint Center", city: "Phoenix" },
  25: { arena: "Moda Center", city: "Portland" },
  26: { arena: "Golden 1 Center", city: "Sacramento" },
  27: { arena: "Frost Bank Center", city: "San Antonio" },
  28: { arena: "Scotiabank Arena", city: "Toronto" },
  29: { arena: "Delta Center", city: "Salt Lake City" },
  30: { arena: "Capital One Arena", city: "Washington" },
};
