// Top NBA players from playoff/play-in teams (2025-26 season)
// Sorted roughly by MVP likelihood
export const NBA_PLAYERS = [
  // Top MVP candidates
  { name: "Nikola Jokic", team: "DEN", team_id: 8 },
  { name: "Shai Gilgeous-Alexander", team: "OKC", team_id: 21 },
  { name: "Luka Doncic", team: "LAL", team_id: 14 },
  { name: "Jayson Tatum", team: "BOS", team_id: 2 },
  { name: "Giannis Antetokounmpo", team: "MIL", team_id: 17 },
  { name: "Anthony Edwards", team: "MIN", team_id: 18 },
  { name: "Donovan Mitchell", team: "CLE", team_id: 6 },
  { name: "Jalen Brunson", team: "NYK", team_id: 20 },
  { name: "Kevin Durant", team: "PHX", team_id: 24 },
  { name: "Stephen Curry", team: "GSW", team_id: 10 },
  { name: "LeBron James", team: "LAL", team_id: 14 },
  { name: "Anthony Davis", team: "LAL", team_id: 14 },
  { name: "Trae Young", team: "ATL", team_id: 1 },
  { name: "Scottie Barnes", team: "TOR", team_id: 28 },
  { name: "James Harden", team: "LAC", team_id: 13 },
  { name: "Kawhi Leonard", team: "LAC", team_id: 13 },
  { name: "Alperen Sengun", team: "HOU", team_id: 11 },
  { name: "Jalen Green", team: "HOU", team_id: 11 },
  { name: "Paolo Banchero", team: "ORL", team_id: 22 },
  { name: "Tyrese Maxey", team: "PHI", team_id: 23 },
  { name: "Joel Embiid", team: "PHI", team_id: 23 },
  { name: "Devin Booker", team: "PHX", team_id: 24 },
  { name: "Jaylen Brown", team: "BOS", team_id: 2 },
  { name: "Derrick White", team: "BOS", team_id: 2 },
  { name: "Darius Garland", team: "CLE", team_id: 6 },
  { name: "Evan Mobley", team: "CLE", team_id: 6 },
  { name: "Jarrett Allen", team: "CLE", team_id: 6 },
  { name: "Karl-Anthony Towns", team: "NYK", team_id: 20 },
  { name: "Mikal Bridges", team: "NYK", team_id: 20 },
  { name: "OG Anunoby", team: "NYK", team_id: 20 },
  { name: "Jamal Murray", team: "DEN", team_id: 8 },
  { name: "Aaron Gordon", team: "DEN", team_id: 8 },
  { name: "Michael Porter Jr.", team: "DEN", team_id: 8 },
  { name: "Rudy Gobert", team: "MIN", team_id: 18 },
  { name: "Julius Randle", team: "MIN", team_id: 18 },
  { name: "Dejounte Murray", team: "ATL", team_id: 1 },
  { name: "Jalen Johnson", team: "ATL", team_id: 1 },
  { name: "LaMelo Ball", team: "CHA", team_id: 4 },
  { name: "Brandon Miller", team: "CHA", team_id: 4 },
  { name: "Jimmy Butler", team: "MIA", team_id: 16 },
  { name: "Bam Adebayo", team: "MIA", team_id: 16 },
  { name: "Tyler Herro", team: "MIA", team_id: 16 },
  { name: "Norman Powell", team: "LAC", team_id: 13 },
  { name: "Ivica Zubac", team: "LAC", team_id: 13 },
  { name: "Draymond Green", team: "GSW", team_id: 10 },
  { name: "Andrew Wiggins", team: "GSW", team_id: 10 },
  { name: "Jonathan Kuminga", team: "GSW", team_id: 10 },
  { name: "Franz Wagner", team: "ORL", team_id: 22 },
  { name: "Jalen Suggs", team: "ORL", team_id: 22 },
  { name: "Anfernee Simons", team: "POR", team_id: 25 },
  { name: "Scoot Henderson", team: "POR", team_id: 25 },
  { name: "RJ Barrett", team: "TOR", team_id: 28 },
  { name: "Immanuel Quickley", team: "TOR", team_id: 28 },
  { name: "Damian Lillard", team: "MIL", team_id: 17 },
  { name: "Khris Middleton", team: "MIL", team_id: 17 },
  { name: "Brook Lopez", team: "MIL", team_id: 17 },
  { name: "Fred VanVleet", team: "HOU", team_id: 11 },
  { name: "Jabari Smith Jr.", team: "HOU", team_id: 11 },
  { name: "Amen Thompson", team: "HOU", team_id: 11 },
  { name: "Chet Holmgren", team: "OKC", team_id: 21 },
  { name: "Jalen Williams", team: "OKC", team_id: 21 },
  { name: "Austin Reaves", team: "LAL", team_id: 14 },
  { name: "Bradley Beal", team: "PHX", team_id: 24 },
];
