-- NBA Teams seed data (balldontlie API IDs)
INSERT INTO nba_teams (id, name, full_name, abbreviation, conference, division, city) VALUES
(1, 'Hawks', 'Atlanta Hawks', 'ATL', 'East', 'Southeast', 'Atlanta'),
(2, 'Celtics', 'Boston Celtics', 'BOS', 'East', 'Atlantic', 'Boston'),
(3, 'Nets', 'Brooklyn Nets', 'BKN', 'East', 'Atlantic', 'Brooklyn'),
(4, 'Hornets', 'Charlotte Hornets', 'CHA', 'East', 'Southeast', 'Charlotte'),
(5, 'Bulls', 'Chicago Bulls', 'CHI', 'East', 'Central', 'Chicago'),
(6, 'Cavaliers', 'Cleveland Cavaliers', 'CLE', 'East', 'Central', 'Cleveland'),
(7, 'Mavericks', 'Dallas Mavericks', 'DAL', 'West', 'Southwest', 'Dallas'),
(8, 'Nuggets', 'Denver Nuggets', 'DEN', 'West', 'Northwest', 'Denver'),
(9, 'Pistons', 'Detroit Pistons', 'DET', 'East', 'Central', 'Detroit'),
(10, 'Warriors', 'Golden State Warriors', 'GSW', 'West', 'Pacific', 'Golden State'),
(11, 'Rockets', 'Houston Rockets', 'HOU', 'West', 'Southwest', 'Houston'),
(12, 'Pacers', 'Indiana Pacers', 'IND', 'East', 'Central', 'Indiana'),
(13, 'Clippers', 'LA Clippers', 'LAC', 'West', 'Pacific', 'LA'),
(14, 'Lakers', 'Los Angeles Lakers', 'LAL', 'West', 'Pacific', 'Los Angeles'),
(15, 'Grizzlies', 'Memphis Grizzlies', 'MEM', 'West', 'Southwest', 'Memphis'),
(16, 'Heat', 'Miami Heat', 'MIA', 'East', 'Southeast', 'Miami'),
(17, 'Bucks', 'Milwaukee Bucks', 'MIL', 'East', 'Central', 'Milwaukee'),
(18, 'Timberwolves', 'Minnesota Timberwolves', 'MIN', 'West', 'Northwest', 'Minnesota'),
(19, 'Pelicans', 'New Orleans Pelicans', 'NOP', 'West', 'Southwest', 'New Orleans'),
(20, 'Knicks', 'New York Knicks', 'NYK', 'East', 'Atlantic', 'New York'),
(21, 'Thunder', 'Oklahoma City Thunder', 'OKC', 'West', 'Northwest', 'Oklahoma City'),
(22, 'Magic', 'Orlando Magic', 'ORL', 'East', 'Southeast', 'Orlando'),
(23, '76ers', 'Philadelphia 76ers', 'PHI', 'East', 'Atlantic', 'Philadelphia'),
(24, 'Suns', 'Phoenix Suns', 'PHX', 'West', 'Pacific', 'Phoenix'),
(25, 'Trail Blazers', 'Portland Trail Blazers', 'POR', 'West', 'Northwest', 'Portland'),
(26, 'Kings', 'Sacramento Kings', 'SAC', 'West', 'Pacific', 'Sacramento'),
(27, 'Spurs', 'San Antonio Spurs', 'SAS', 'West', 'Southwest', 'San Antonio'),
(28, 'Raptors', 'Toronto Raptors', 'TOR', 'East', 'Atlantic', 'Toronto'),
(29, 'Jazz', 'Utah Jazz', 'UTA', 'West', 'Northwest', 'Utah'),
(30, 'Wizards', 'Washington Wizards', 'WAS', 'East', 'Southeast', 'Washington')
ON CONFLICT (id) DO NOTHING;
